version: 2

archives:
  - format: tar.gz
    files:
      - src: '*.go'
      - src: 'go.mod'
      - src: 'go.sum'
      - src: 'LICENSE*'
      - src: 'README*'
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: sup2ak
    name: github-stats-api-go

snapshot:
  name_template: "{{ incpatch .Version }}-next"